# -*- coding: utf-8 -*-
"""2502110075- LAB-05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FFXxQ9t0a05tlKyZ2pm7zMDtr7yKTH9K
"""

#IT-12
raw_line = "  PE-26-0137 ; 25.02 ; DAY  "

fields = raw_line.strip().split(";")
code = fields[0].strip()
dia = float(fields[1])
shift = fields[2].strip().upper()

print("Part Code:", code)
print("Diameter:", dia)
print("Shift:", shift)

print("Dia + 0.01 =", dia + 0.01)

#IT-10
log_lines = [
    "  PE-26-0101 ; 25.02 ; DAY  ",
    "PE-26-0102;24.95;DAY",
    " PE-26-0103 ; 25.08 ; DAY ",
    "PE-26-0104 ; 24.90 ; DAY",
    "  PE-26-0105 ; 25.01 ; DAY ",
    "PE-26-0106; 25.12 ; DAY",
    " PE-26-0107 ; 24.88 ; DAY",
    "PE-26-0108 ; 25.00 ; DAY ",
    "  PE-26-0109 ; 25.05 ; DAY",
    "PE-26-0110 ; 24.99 ; DAY"
]

diameters = [float(line.split(";")[1]) for line in log_lines]

print(f"Total Count: {len(diameters)}")
print(f"Average Diameter: {sum(diameters) / len(diameters):.2f}")
print(f"Minimum Diameter: {min(diameters)}")
print(f"Maximum Diameter: {max(diameters)}")

# IT-8

log_lines = [
    "  PE-26-0101 ; 25.02 ; DAY  ",
    "PE-26-0102;24.92;DAY",
    " PE-26-0103 ; 25.08 ; DAY ",
    "PE-26-0104 ; 24.90 ; DAY",
    "  PE-26-0105 ; 25.01 ; DAY ",
    "PE-26-0106; 25.12 ; DAY",
    " PE-26-0107 ; 24.88 ; DAY",
    "PE-26-0108 ; 25.00 ; DAY ",
    "  PE-26-0109 ; 25.05 ; DAY",
    "PE-26-0110 ; 24.99 ; DAY"
]

accepted_dias = []
rework_dias = []
scrap_dias = []
scrapped_codes = []

for line in log_lines:
    fields = line.strip().split(";")
    code = fields[0].strip()
    dia = float(fields[1])


    if 24.95 <= dia <= 25.05:
        accepted_dias.append(dia)
    elif dia < 24.95:
        rework_dias.append(dia)
    else:
        scrap_dias.append(dia)
        scrapped_codes.append(code)

print("--- SHIFT REPORT ---")
print(f"Accepted Count : {len(accepted_dias)}")
print(f"Rework Count   : {len(rework_dias)}")
print(f"Scrap Count    : {len(scrap_dias)}")

if accepted_dias:
    accepted_avg = sum(accepted_dias) / len(accepted_dias)
    print(f"Accepted Avg   : {accepted_avg:.2f}")

print(f"Scrapped Part Codes: {scrapped_codes}")

# IT-6

all_log_lines = [
    "PE-26-0101 ; 25.02 ; DAY",
    "PE-26-0102 ; 25.08 ; DAY",
    "PE-26-0103 ; 25.12 ; DAY",
    "PE-26-0104 ; 24.99 ; DAY",
    "PE-26-0201 ; 25.01 ; NIGHT",
    "PE-26-0202 ; 25.09 ; NIGHT",
    "PE-26-0102 ; 25.10 ; NIGHT",
    "PE-26-0204 ; 24.98 ; NIGHT"
]

day_accepted = 0
day_total = 0
night_accepted = 0
night_total = 0

day_scrap_codes = set()
night_scrap_codes = set()

for line in all_log_lines:
    fields = line.strip().split(";")
    code = fields[0].strip()
    dia = float(fields[1])
    shift = fields[2].strip().upper()

    is_accepted = 24.95 <= dia <= 25.05

    if shift == "DAY":
        day_total += 1
        if is_accepted:
            day_accepted += 1
        elif dia > 25.05:
            day_scrap_codes.add(code)

    elif shift == "NIGHT":
        night_total += 1
        if is_accepted:
            night_accepted += 1
        elif dia > 25.05:
            night_scrap_codes.add(code)


day_accept_rate = (day_accepted / day_total * 100) if day_total else 0
night_accept_rate = (night_accepted / night_total * 100) if night_total else 0

print("--- SHIFT COMPARISON REPORT ---")
print(f"Day Shift Accept Rate   : {day_accept_rate:.1f}%")
print(f"Night Shift Accept Rate : {night_accept_rate:.1f}%")


both_scrap = day_scrap_codes & night_scrap_codes
unique_scrap = day_scrap_codes ^ night_scrap_codes

print(f"\nPart codes scrapped in BOTH shifts : {both_scrap}")
print(f"Part codes unique to ONE shift     : {unique_scrap}")